name: get_bootimg_from_payload.bin

on:
  watch:
    types: [started]
    
env:
  ROM_URL:  https://dl.google.com/dl/android/aosp/cheetah-td1a.220804.009.a2-factory-8e7393e1.zip 

  TZ: Asia/Shanghai

jobs:
  make:
    runs-on: ubuntu-latest

    steps:
          
    - name: Download the tools
      run: |
       cd ~
       uname -a
       sudo -E apt-get -qq update
       wget https://github.com/ssut/payload-dumper-go/releases/download/1.2.2/payload-dumper-go_1.2.2_linux_amd64.tar.gz
       mkdir ROMFILE
       tar -zxvf payload-dumper-go_1.2.2_linux_amd64.tar.gz -C ROMFILE
       ls ROMFILE
       
  
    - name: Download the ROM
      run: |
       cd ~
       wget -O rom.zip $ROM_URL
       ls -l
       
    - name: unzip the ROM1
      run: |
       cd ~
       unzip rom.zip
       unzip image-cheetah-td1a.220804.009.a2.zip -d ROMFILE 
       dir
       ls -l
       
              
    - name: extract the payload.bin
      run: |
       cd ~
       cd ROMFILE
       ./payload-dumper-go -l payload.bin
       ./payload-dumper-go -p logo,splash,imagefv -o img payload.bin 
       ls -l
       cd img
       ls -l
       
    - name : Upload images logo
        cd ~
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: logo_Payload-images
        path: ~/ROMFILE/logo.*

    - name : Upload images splash
        cd ~
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: splash_Payload-images
        path: ~/ROMFILE/firmware-update/splash.*

    - name : Upload images imagefv
        cd ~
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: imagefv_Payload-images
        path: ~/ROMFILE/firmware-update/imagefv.*

    - name : Upload images
        cd ~
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Payload-images
        path: ~/ROMFILE/img/
        
