name: get_bootimg_from_payload.bin

on:
  watch:
    types: [started]
    
env:
  ROM_URL:  https://software.download.prss.microsoft.com/dbazure/Win10_22H2_China_GGK_Chinese_Simplified_x64.iso?t=9cbce982-d46e-4d95-863c-77474ea59bef&e=1672681157&h=f6903343f3dc8dcbe8b18df201f0b4629f4b2075791d4d0a9b2bad029233be23
  ROM_NAME: alioth_images_V12.5.3.0.RKHCNXM_20210517.0000.00_11.0_cn

  TZ: Asia/Shanghai

jobs:
  make:
    runs-on: ubuntu-latest

    steps:

  
    - name: Download the ROM
      run: |
       cd ~
       wget -O rom.iso $ROM_URL

   
    - name: unzip the ROM
      run: |
       cd ~
       stat rom.iso
       sha256sum rom.iso
       sha256sum rom.iso >sha.txt
       ls -l
       tree
   
    - name : Upload images1
        cd ~
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: 12S_PRO_logo_Payload-images
        path: ~/mondrian_images_V14.0.11.0.TMNCNXM_13.0/images/imagefv.*
        
    - name : Upload images2
        cd ~
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: 12S_PRO_splash_Payload-images
        path: ~/sha.txt
