name: get_bootimg_from_payload.bin

on:
  watch:
    types: [started]
    
env:
  ROM_URL:  https://software.download.prss.microsoft.com/dbazure/Win11_22H2_Chinese_Simplified_x64v1.iso?t=e38c728c-0dda-405f-b750-7e937ae49e9d&e=1672682332&h=d87669f0583f9510bdd0e5824cccbc8732b9c2a07452cb2f483a42345f6ce4d2
  ROM_NAME: alioth_images_V12.5.3.0.RKHCNXM_20210517.0000.00_11.0_cn

  TZ: Asia/Shanghai

jobs:
  make:
    runs-on: ubuntu-latest

    steps:

  
    - name: Download the ROM
      run: |
       cd ~
       wget -O rom.iso $ROM_URL
   
    - name: unzip the ROM
      run: |
       cd ~
       sha256sum rom.iso
       sha256sum rom.iso >sha.txt
       ls -l
       tree
   
    - name : Upload images1
        cd ~
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: 12S_PRO_logo_Payload-images
        path: ~/mondrian_images_V14.0.11.0.TMNCNXM_13.0/images/imagefv.*
        
    - name : Upload images2
        cd ~
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: 12S_PRO_splash_Payload-images
        path: ~/sha.txt
